genres = ['Zombie',
 'Colonial United States romance',
 'Humour',
 'Apocalyptic and post-apocalyptic fiction',
 'Comic science fiction',
 'Comedy of manners',
 'Locked room mystery',
 'Psychology',
 'Neuroscience',
 'Autobiographical novel',
 'New York Times Best Seller list',
 'Sword and planet',
 'Invasion literature',
 'Albino bias',
 'Comic book',
 'Techno-thriller',
 'Roman à clef',
 'Literary fiction',
 'Wuxia',
 'Alien invasion',
 'Georgian romance',
 'Zombies in popular culture',
 'New Weird',
 'Subterranean fiction',
 'Vampire fiction',
 'Social novel',
 'Treatise',
 'Religion',
 'Memoir',
 "Boys' school stories",
 'Sports',
 'Biographical novel',
 'Science fantasy',
 'Edisonade',
 'Photography',
 'Historical romance',
 'Non-fiction',
 'Play',
 'Detective fiction',
 'Prose poetry',
 'Travel',
 'Western fiction',
 'Cabal',
 'Education',
 'Epistolary novel',
 'Historical fiction',
 'Social science fiction',
 'Anti-nuclear',
 'Political philosophy',
 'Future history',
 'Nature',
 'Satire',
 'Urban fantasy',
 'Fable',
 'Economics',
 'Whodunit',
 'Tragicomedy',
 'Low fantasy',
 'Utopian and dystopian fiction',
 'Transgender and transsexual fiction',
 'Marketing',
 'Collage',
 'Existentialism',
 'War novel',
 'Spy fiction',
 'Comic novel',
 'Chick lit',
 'Transhumanism',
 'Fairy tale',
 'Pastiche',
 'Conspiracy fiction',
 'Speculative fiction',
 'Novella',
 'Dystopia',
 'Feminist science fiction',
 'Cyberpunk',
 'Sociology',
 'Cozy',
 'Polemic',
 'Literary criticism',
 'Fantastique',
 'Fiction',
 'Comics',
 'Comedy',
 'Suspense',
 'Field guide',
 'Biopunk',
 'Science Fiction',
 'Urban fiction',
 'English public-school stories',
 'Soft science fiction',
 'Mathematics',
 'Coming of age',
 'Catastrophic literature',
 'Historical whodunnit',
 'Parallel novel',
 'Creative nonfiction',
 'Contemporary fantasy',
 'Human extinction',
 'Literary realism',
 'Literary theory',
 'Erotica',
 'Chivalric romance',
 'Postcyberpunk',
 'Juvenile fantasy',
 'Postmodernism',
 'Music',
 'Modernism',
 'Gamebook',
 'Superhero fiction',
 'Utopian fiction',
 'Bildungsroman',
 'Post-holocaust',
 'Short story',
 'Ghost story',
 "Children's literature",
 'Space western',
 'Politics',
 'Sword and sorcery',
 'Fictional crossover',
 'Industrial novel',
 'LGBT literature',
 'High fantasy',
 'Experimental literature',
 'Travel literature',
 'Self-help',
 'Popular culture',
 'Fantasy of manners',
 'Horror',
 'Hardboiled',
 'Epic Science Fiction and Fantasy',
 'Crime Fiction',
 'Gay novel',
 'Spirituality',
 'Morality play',
 'Elizabethan romance',
 'History',
 'School story',
 'Inspirational',
 'Dark fantasy',
 'Picture book',
 'Foreign legion',
 'American Gothic Fiction',
 'Gay Themed',
 'Light novel',
 'Biography',
 'Dying Earth subgenre',
 'Sea story',
 'Heroic fantasy',
 'Fantasy',
 'Young adult literature',
 'Supernatural',
 'Picaresque novel',
 'Novel',
 'Graphic novel',
 'Regency romance',
 'Youth',
 'Mystery',
 'First-person narrative',
 'Gothic fiction',
 'Anti-war',
 'Bit Lit',
 'Hard science fiction',
 'Black comedy',
 'Reference',
 'Ergodic literature',
 'Popular science',
 'Anthropology',
 'Fairytale fantasy',
 'Western',
 'Cookbook',
 'Bangsian fantasy',
 'Mashup',
 'Religious text',
 'Parody',
 'True crime',
 'Adventure',
 'Computer Science',
 'Campus novel',
 'Autobiography',
 'Conspiracy',
 'Space opera',
 'Police procedural',
 'Magic realism',
 'Encyclopedia',
 'Absurdist fiction',
 'Philosophy',
 'Planetary romance',
 'Social criticism',
 'Robinsonade',
 'Business',
 'Naval adventure',
 'Essay',
 'Romantic comedy',
 'Military history',
 'Historical novel',
 'Historical fantasy',
 'Prose',
 'Role-playing game',
 'Steampunk',
 'Military science fiction',
 'Drama',
 'Autobiographical comics',
 'Social sciences',
 'Comic fantasy',
 'Adventure novel',
 'Serial',
 'Scientific romance',
 'Poetry',
 'Alternate history',
 'Non-fiction novel',
 'Social commentary',
 'Anthology',
 'Metaphysics',
 'Time travel',
 'Farce',
 'Künstlerroman',
 'Medieval romance',
 'Paranormal romance',
 'Science',
 'Psychological novel',
 'Thriller',
 'Personal journal',
 'Pornography',
 'Lost World',
 'Indian chick lit',
 'Romance novel']